### PR TITLE
Update in publishsettings.targets with correct publishUrl

### PR DESCRIPTION
**Pull request by sebastiantecsi**
Event that publishsettings.targets looks that is not in use in any .csproj file it should be updated with correct publishUrl.

### CODE REVIEW

**Comment by jeanfrancoislarente** [comment]
Thanks @sebastiantecsi  - can you please re-target against contrib branch? Will make it easier to pull in your changes.

(yes, we need additional instructions around contributions)

**Comment by sebastiantecsi** [comment]
@jeanfrancoislarente Please have another look. I have changed the target to contrib.

**Review by jeanfrancoislarente — APPROVED** [review]

**Comment by jeanfrancoislarente** [comment]
Merging to contrib, will be a little bit before it makes it back into main (next release).

Thanks!!

**Comment by jeanfrancoislarente** [comment]
Update: This was merged to develop internally - will still take a little while before it makes it into the "main" branch

**Pull request merged**
