### PR TITLE
Update Usage.md with exact Docker Desktop version requirements

### PR DESCRIPTION
**Pull request by tamas-tarnok**

### CODE REVIEW

**Comment by jflheureux** [comment]
Thank you Tamás for that pull request. We will unfortunately not merge it as we have pending changes waiting to be pushed to GitHub in the Sitecore private origin of this repository that allow using the latest version of Docker Desktop:
- Switch the Linux containers to Windows versions.
- Switch to Docker Compose V2.

These changes are expected to be pushed to the GitHub origin in the next weeks.

**Comment by tamas-tarnok** [comment]
> Thank you Tamás for that pull request. We will unfortunately not merge it as we have pending changes waiting to be pushed to GitHub in the Sitecore private origin of this repository that allow using the latest version of Docker Desktop:
> 
> * Switch the Linux containers to Windows versions.
> * Switch to Docker Compose V2.
> 
> These changes are expected to be pushed to the GitHub origin in the next weeks.

I just thought this minor documentation fix can be beneficial for others in the meanwhile, I just found this info on Sitecore Slack.

**Comment by jflheureux** [comment]
Definitely. I will keep this PR open until we push the changes so that other users can find the information.

**Comment by adoprog** [comment]
Closing this, latest Docker is supported and the changes were pushed to this repo last year.

**Pull request closed without merging**
